version: "3.8"
services:
  kstratum:
    build: ./kstratum
    container_name: kstratum
    restart: unless-stopped
    ports:
      - "16112:16112"  # Stratum port
    environment:
      - KASPAD_HOST=kaspad
      - KASPAD_PORT=16110
    networks:
      - kas20_default

networks:
  kas20_default:
    external: true
